# docker-compose.yml
version:                   "3"
networks:
  webappnetwork:
    driver:                bridge
services:
  client:
    build:                 ./client
    restart:               always
    ports:
        - "3000:3000"
    volumes:
        - ./client:/client
        - /client/node_modules
    links:
        - api
    networks:
        webappnetwork
  api:
    build:                 ./api
    restart:               always
    ports:
        - "9000:9000"
    volumes:
        - ./api:/api
        - /api/node_modules
    depends_on:
        - mongodb
    networks:
        webappnetwork
  mariadb:
    image:                 mariadb
    container_name:        mariadb
    restart:               always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    networks:
            - webappnetwork
