# docker-compose.yml
version:                   "3"
networks:
  webappnetwork:
    driver:                bridge
services:
  client:
    build:                 ./client
    restart:               always
    ports:
        - "3000:3000"
    volumes:
        - ./client:/client
        - /client/node_modules
    links:
        - api
    networks:
        - webappnetwork
  api:
    build:                 ./api
    restart:               always
    ports:
        - "8000:8000"
    volumes:
        - ./api:/api
        - /api/node_modules
    depends_on:
        - mariadb
    networks:
        - webappnetwork
  mariadb:
    build:                 ./mariadb
    container_name:        mariadb
    restart:               always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - webappnetwork
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - webappnetwork
